name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Ensure `environment.ts` file exists
      - name: Ensure environment.ts file exists
        run: |
          FILE="src/environments/environment.ts"
          if [ ! -f "$FILE" ]; then
            echo "Creating environment.ts..."
            echo "export const environment = {" > $FILE
            echo "  production: false," >> $FILE
            echo "  tmdbApiKey: 'your_dummy_api_key'," >> $FILE
            echo "  assetsBaseUrl: '/'," >> $FILE
            echo "  tmdbBaseUrl: 'https://api.themoviedb.org/3/'" >> $FILE
            echo "};" >> $FILE
            echo "environment.ts created successfully."
          else
            echo "environment.ts already exists."
          fi

      # Step 5: Ensure `environment.prod.ts` file exists
      - name: Ensure environment.prod.ts file exists
        run: |
          FILE="src/environments/environment.prod.ts"
          if [ ! -f "$FILE" ]; then
            echo "Creating environment.prod.ts..."
            echo "export const environment = {" > $FILE
            echo "  production: true," >> $FILE
            echo "  tmdbApiKey: 'your_dummy_api_key'," >> $FILE
            echo "  assetsBaseUrl: '/'," >> $FILE
            echo "  tmdbBaseUrl: 'https://api.themoviedb.org/3/'" >> $FILE
            echo "};" >> $FILE
            echo "environment.prod.ts created successfully."
          else
            echo "environment.prod.ts already exists."
          fi

      # Step 6: Lint both environment files
      - name: Lint environment.ts and environment.prod.ts
        run: |
          npx eslint src/environments/environment.ts --fix
          npx eslint src/environments/environment.prod.ts --fix

      # Step 7: Run tests in virtual display
      - name: Run tests in virtual display
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          xvfb-run --server-args="-screen 0 1920x1080x24" npm test -- --watch=false

      # Step 8: Lint the entire codebase
      - name: Lint the code
        run: npm run lint

      # Step 9: Build the project
      - name: Build the project
        run: npm run build
